import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { BALANCE_STRATEGIES, simulateBalance } from "./balance-model.js";

const weeks = 8;
const results = Object.keys(BALANCE_STRATEGIES).map((strategyId) => simulateBalance(strategyId, { weeks }));
const report = renderReport(results, weeks);

if (process.argv.includes("--write")) {
  const outputUrl = new URL("./BALANCE-REPORT.md", import.meta.url);
  await writeFile(fileURLToPath(outputUrl), report);
  console.log(`Wrote ${fileURLToPath(outputUrl)}`);
} else {
  console.log(report);
}

export function renderReport(rows, simulatedWeeks) {
  const required = new Set(["fast", "regrow", "slow", "mixed", "quality"]);
  const covered = rows.filter((row) => required.has(row.strategyId)).map((row) => row.strategyId);
  if (covered.length !== required.size) throw new Error("The required balance strategy set is incomplete.");

  const dominant = findUniversalDominant(rows.filter((row) => required.has(row.strategyId)));
  const nonViable = rows.filter((row) => row.netCoinsPerWeek <= 0).map((row) => row.strategy);
  const bottleneckTotals = sumBottlenecks(rows);
  const bottleneckText = Object.entries(bottleneckTotals)
    .sort((a, b) => b[1] - a[1])
    .map(([key, value]) => `${key.replaceAll("_", " ")} (${value})`)
    .join(", ");

  return `# Spring Farming v1 — deterministic balance report

Generated by \`node balance-sim.mjs --write\` from the checked-in crop and AP constants.

## Assumptions

- ${simulatedWeeks} consecutive seven-day Spring Weeks; exactly three persistent Land.
- Runtime starting state: 3 coins, one prepared Plot, two Wild Soil, 8 AP/day and a two-charge Watering Can.
- Preparing each Wild Soil costs one Sickle AP plus one Hoe AP.
- A Store restock day pays a 2 AP round trip; Seed purchases and shipping remain free actions.
- Rain follows the runtime forecast and waters existing thirsty crops/empty Plots on day 6. Baby Radishes require an explicit watering choice.
- Produce ships on the harvest night. Ordinary and Choice Produce are both worth 1 coin each; Choice value lives in persistent care memories.
- Each policy protects existing crops before expanding. The mixed policies rotate through all five crops; the Quality policy tends every planted crop once per harvest cycle.
- The model is intentionally headless and deterministic. It measures economy/AP/Land pressure, not gesture speed or emotional preference.

## Strategy results

| Strategy | Coins/week | Net/week after Seeds | Harvests/week | AP use | Land use | Care memories | Choice harvests | Ending coins |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
${rows.map((row) => `| ${row.strategy} | ${row.coinsPerWeek} | ${row.netCoinsPerWeek} | ${row.harvestsPerWeek} | ${row.apUsePercent}% | ${row.landUsePercent}% | ${row.careMemories}/5 | ${row.choiceHarvests} | ${row.endingCoins} |`).join("\n")}

## Crop output and pressure

${rows.map((row) => `- **${row.strategy}:** produce ${formatCropMap(row.cropProduce)}; AP bottlenecks ${formatBottlenecks(row.bottlenecks)}.`).join("\n")}

## Findings

- Dominance check: ${dominant ? `${dominant} beats every other required policy on net income without using more AP.` : "no required policy universally dominates the others on both net income and AP use."}
- Crop viability check: ${nonViable.length ? `${nonViable.join(", ")} failed to return positive net coins and requires a design review.` : "every monocrop behavior returns positive net coins over the review horizon."}
- Aggregate observed bottlenecks: ${bottleneckText || "none"}.
- Quality is deterministic and intentionally does not raise income. Its explicit Tend actions consume AP in exchange for filling five persistent crop-care memories.
- Baby Radish and Full Radish are reported separately so the early-harvest decision cannot hide inside an average.

## Tuning decision

The first simulator pass exposed two behavior-aligned outliers: Green Beans at four Produce every two regrow nights overwhelmed rotation, and a per-unit ×2 Choice payout made Quality economically mandatory. Spring v1 therefore uses three Green Beans per harvest, keeps Choice Produce at the ordinary shipment rate, and gives Quality five persistent crop-care memories instead. Potato remains the required deterministic 2 + 2, but its Seed moved from two coins to one because the second Hoe AP already supplies its cost. The checked-in second pass shows no universal dominant policy and no non-viable crop; further tuning waits for hands-on evidence.
`;
}

function findUniversalDominant(rows) {
  const candidate = rows.find((row) => rows.every((other) => row === other
    || (row.netCoinsPerWeek >= other.netCoinsPerWeek && row.apUsePercent <= other.apUsePercent)));
  return candidate?.strategy ?? null;
}

function sumBottlenecks(rows) {
  return rows.reduce((totals, row) => {
    Object.entries(row.bottlenecks).forEach(([key, value]) => {
      totals[key] = (totals[key] ?? 0) + value;
    });
    return totals;
  }, {});
}

function formatCropMap(map) {
  const entries = Object.entries(map).filter(([, value]) => value > 0);
  return entries.length ? entries.map(([cropId, value]) => `${cropId.replaceAll("_", " ")} ${value}`).join(", ") : "none";
}

function formatBottlenecks(map) {
  const entries = Object.entries(map).filter(([, value]) => value > 0);
  return entries.length ? entries.map(([key, value]) => `${key.replaceAll("_", " ")} ${value}`).join(", ") : "none";
}
