export const GAME = Object.freeze({
  version: 21,
  goalCoins: 6,
  cropGrowthDays: 2,
  actionPointsPerDay: 8,
  seasonName: "Spring",
  seasonLengthDays: 7,
  weatherByDay: Object.freeze(["sunny", "sunny", "sunny", "sunny", "sunny", "rainy", "sunny"]),
  farmFieldCapacity: 3,
  wateringCanCapacity: 2,
  storageKey: "little-valley-physical-board-v21",
  legacyStorageKeys: Object.freeze(["little-valley-physical-board-v20", "little-valley-physical-board-v19", "little-valley-physical-board-v18", "little-valley-physical-board-v17", "little-valley-physical-board-v16"]),
});

export function weatherForDay(day) {
  return GAME.weatherByDay[(Math.max(1, day) - 1) % GAME.weatherByDay.length];
}

export const CROPS = Object.freeze({
  carrot: Object.freeze({
    id: "carrot",
    name: "Carrots",
    storeLabel: "Carrot",
    seedTypeId: "carrot_seeds",
    plantedTypeId: "planted_carrots",
    wateredTypeId: "watered_carrots",
    readyTypeId: "ready_carrots",
    produceTypeId: "carrots",
    choiceProduceTypeId: "choice_carrots",
    growthDays: 2,
    regrowDays: 0,
    harvestAmount: 3,
    seedBundleCost: 1,
    seedBundleAmount: 1,
    behavior: "Fast one-shot",
    yieldLabel: "3 Carrots",
    afterHarvestLabel: "Plot clears",
    harvestStages: Object.freeze([
      Object.freeze({ state: "ready", amount: 3, next: "clear", complete: true }),
    ]),
  }),
  green_bean: Object.freeze({
    id: "green_bean",
    name: "Green Beans",
    storeLabel: "Beans",
    seedTypeId: "green_bean_seeds",
    plantedTypeId: "planted_green_beans",
    wateredTypeId: "watered_green_beans",
    readyTypeId: "ready_green_beans",
    produceTypeId: "green_beans",
    choiceProduceTypeId: "choice_green_beans",
    growthDays: 3,
    regrowDays: 2,
    harvestAmount: 3,
    seedBundleCost: 2,
    seedBundleAmount: 1,
    behavior: "Persistent regrow",
    yieldLabel: "3 Green Beans",
    afterHarvestLabel: "Vines regrow in 2 nights",
    harvestStages: Object.freeze([
      Object.freeze({ state: "ready", amount: 3, next: "regrow", complete: true }),
    ]),
  }),
  potato: Object.freeze({
    id: "potato",
    name: "Potatoes",
    storeLabel: "Potato",
    seedTypeId: "potato_seeds",
    plantedTypeId: "planted_potatoes",
    wateredTypeId: "watered_potatoes",
    readyTypeId: "ready_potatoes",
    partialTypeId: "potato_mounds",
    produceTypeId: "potatoes",
    choiceProduceTypeId: "choice_potatoes",
    growthDays: 2,
    regrowDays: 0,
    harvestAmount: 4,
    harvestTool: "hoe",
    harvestSteps: Object.freeze([2, 2]),
    seedBundleCost: 1,
    seedBundleAmount: 1,
    behavior: "Two Hoe digs",
    yieldLabel: "4 total · 2 + 2",
    afterHarvestLabel: "Hoe · two digs, then Plot clears",
    harvestStages: Object.freeze([
      Object.freeze({ state: "ready", amount: 2, next: "partial", complete: false }),
      Object.freeze({ state: "partial_harvest", amount: 2, next: "clear", complete: true }),
    ]),
  }),
  cauliflower: Object.freeze({
    id: "cauliflower",
    name: "Cauliflowers",
    storeLabel: "Cauliflower",
    seedTypeId: "cauliflower_seeds",
    plantedTypeId: "planted_cauliflowers",
    wateredTypeId: "watered_cauliflowers",
    readyTypeId: "ready_cauliflowers",
    produceTypeId: "cauliflowers",
    choiceProduceTypeId: "choice_cauliflowers",
    growthDays: 4,
    regrowDays: 0,
    harvestAmount: 9,
    seedBundleCost: 3,
    seedBundleAmount: 1,
    behavior: "Slow large payoff",
    yieldLabel: "9 Cauliflowers",
    afterHarvestLabel: "Plot clears after a long commitment",
    harvestStages: Object.freeze([
      Object.freeze({ state: "ready", amount: 9, next: "clear", complete: true }),
    ]),
  }),
  radish: Object.freeze({
    id: "radish",
    name: "Radishes",
    storeLabel: "Radish",
    seedTypeId: "radish_seeds",
    plantedTypeId: "planted_radishes",
    wateredTypeId: "watered_radishes",
    earlyTypeId: "baby_radishes",
    readyTypeId: "ready_radishes",
    produceTypeId: "radishes",
    choiceProduceTypeId: "choice_radishes",
    growthDays: 3,
    earlyReadyRemainingDays: 2,
    regrowDays: 0,
    harvestAmount: 5,
    seedBundleCost: 1,
    seedBundleAmount: 1,
    behavior: "Early-or-full harvest",
    yieldLabel: "2 baby now or 5 full",
    afterHarvestLabel: "Harvest baby, or water twice more",
    harvestStages: Object.freeze([
      Object.freeze({ state: "early_ready", amount: 2, next: "clear", complete: true, label: "Baby" }),
      Object.freeze({ state: "ready", amount: 5, next: "clear", complete: true, label: "Full" }),
    ]),
  }),
});

export const ACTION_COSTS = Object.freeze({
  travel: 1,
  clear_grass: 1,
  till_soil: 1,
  refill_watering_can: 1,
  water_plot: 1,
  sow: 1,
  sow_watered: 1,
  water_crop: 1,
  harvest_crop: 1,
  tend_crop: 1,
  remove_crop: 1,
});

export const AREAS = Object.freeze([
  Object.freeze({ id: "farm", name: "Home Farm", landmarkId: "farm-landmark" }),
  Object.freeze({ id: "town", name: "Valley Town", landmarkId: "town-landmark" }),
]);

const art = (filename) => `./assets/${filename}`;

export const CARD_DEFS = Object.freeze({
  farmer: {
    name: "Farmer",
    kind: "Person",
    description: "Does the work, carries one item, and harvests mature crops by hand.",
    art: art("farmer.png"),
    artShape: "square",
  },
  wild_soil: {
    name: "Wild Soil",
    kind: "Land",
    description: "Grass and stones cover workable earth.",
    art: art("wild-soil.png"),
  },
  cleared_ground: {
    name: "Cleared Ground",
    kind: "Land",
    description: "The grass is cut. The firm soil still needs the Hoe.",
    art: art("cleared-ground.png"),
    badge: "Untilled",
  },
  empty_plot: {
    name: "Empty Plot",
    kind: "Land",
    description: "Cleared soil waiting for seed.",
    art: art("empty-plot.png"),
  },
  watered_empty_plot: {
    name: "Watered Plot",
    kind: "Land",
    description: "Cleared and watered soil waiting for seed.",
    art: art("watered-plot.png"),
    badge: "Watered",
  },
  planted_carrots: {
    name: "Carrot Plot",
    kind: "Crop",
    description: "Planted, but still thirsty.",
    art: art("young-carrots.png"),
    badge: "Thirsty",
    cropId: "carrot",
    cropState: "thirsty",
  },
  watered_carrots: {
    name: "Carrot Plot",
    kind: "Crop",
    description: "Watered. Growing with time.",
    art: art("watered-carrots.png"),
    badge: "Watered",
    cropId: "carrot",
    cropState: "watered",
  },
  ready_carrots: {
    name: "Mature Carrots",
    kind: "Crop",
    description: "Ready to pull from the soil.",
    art: art("harvest.png"),
    badge: "Ready",
    cropId: "carrot",
    cropState: "ready",
  },
  carrot_seeds: {
    name: "Carrot Seeds",
    kind: "Item",
    description: "A Person can pick these up for an Empty Plot.",
    art: art("carrot-seeds.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "carrot",
    cropState: "seeds",
  },
  planted_green_beans: {
    name: "Green Bean Plot",
    kind: "Crop",
    description: "Young vines are climbing, but the soil is thirsty.",
    art: art("young-green-beans.png"),
    badge: "Thirsty",
    cropId: "green_bean",
    cropState: "thirsty",
  },
  watered_green_beans: {
    name: "Green Bean Plot",
    kind: "Crop",
    description: "Watered vines grow toward their next harvest.",
    art: art("watered-green-beans.png"),
    badge: "Watered",
    cropId: "green_bean",
    cropState: "watered",
  },
  ready_green_beans: {
    name: "Mature Green Beans",
    kind: "Crop",
    description: "Ready to pick. The vines remain for another harvest.",
    art: art("mature-green-beans.png"),
    badge: "Ready",
    cropId: "green_bean",
    cropState: "ready",
  },
  green_bean_seeds: {
    name: "Green Bean Seeds",
    kind: "Item",
    description: "One seed starts a slower crop that regrows after harvest.",
    art: art("green-bean-seeds.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "green_bean",
    cropState: "seeds",
  },
  planted_potatoes: {
    name: "Potato Plot",
    kind: "Crop",
    description: "Young Potato plants are growing over dry soil.",
    art: art("young-potatoes.png"),
    badge: "Thirsty",
    cropId: "potato",
    cropState: "thirsty",
  },
  watered_potatoes: {
    name: "Potato Plot",
    kind: "Crop",
    description: "Watered Potato plants grow above hidden tubers.",
    art: art("watered-potatoes.png"),
    badge: "Watered",
    cropId: "potato",
    cropState: "watered",
  },
  ready_potatoes: {
    name: "Mature Potatoes",
    kind: "Crop",
    description: "The full mounds are ready to dig with the Hoe.",
    art: art("mature-potatoes.png"),
    badge: "Dig",
    cropId: "potato",
    cropState: "ready",
  },
  potato_mounds: {
    name: "Potato Mounds",
    kind: "Crop",
    description: "The first dig found Potatoes. Four closed mounds still need the Hoe.",
    art: art("potato-mounds.png"),
    badge: "Dig again",
    cropId: "potato",
    cropState: "partial_harvest",
  },
  potato_seeds: {
    name: "Potato Seeds",
    kind: "Item",
    description: "Seed Potatoes grow into a root crop harvested in two digs.",
    art: art("potato-seeds.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "potato",
    cropState: "seeds",
  },
  planted_cauliflowers: {
    name: "Cauliflower Plot",
    kind: "Crop",
    description: "Young Cauliflowers need patient care and four watered nights.",
    art: art("young-cauliflowers.png"),
    badge: "Thirsty",
    cropId: "cauliflower",
    cropState: "thirsty",
  },
  watered_cauliflowers: {
    name: "Cauliflower Plot",
    kind: "Crop",
    description: "Watered Cauliflowers are slowly forming broad white heads.",
    art: art("watered-cauliflowers.png"),
    badge: "Watered",
    cropId: "cauliflower",
    cropState: "watered",
  },
  ready_cauliflowers: {
    name: "Mature Cauliflowers",
    kind: "Crop",
    description: "A long Land commitment is ready for one large hand harvest.",
    art: art("mature-cauliflowers.png"),
    badge: "Ready",
    cropId: "cauliflower",
    cropState: "ready",
  },
  cauliflower_seeds: {
    name: "Cauliflower Seeds",
    kind: "Item",
    description: "A slow Spring crop with a large harvest after four watered nights.",
    art: art("cauliflower-seeds.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "cauliflower",
    cropState: "seeds",
  },
  planted_radishes: {
    name: "Radish Plot",
    kind: "Crop",
    description: "Quick Radish sprouts need one watered night to reach their baby harvest.",
    art: art("young-radishes.png"),
    badge: "Thirsty",
    cropId: "radish",
    cropState: "thirsty",
  },
  watered_radishes: {
    name: "Radish Plot",
    kind: "Crop",
    description: "Watered Radishes are growing toward their next harvest stage.",
    art: art("watered-radishes.png"),
    badge: "Watered",
    cropId: "radish",
    cropState: "watered",
  },
  baby_radishes: {
    name: "Baby Radishes",
    kind: "Crop",
    description: "Harvest two now to free the Land, or water deliberately to keep growing.",
    art: art("baby-radishes.png"),
    badge: "Harvest or grow",
    cropId: "radish",
    cropState: "early_ready",
  },
  ready_radishes: {
    name: "Full Radishes",
    kind: "Crop",
    description: "Fully grown Radishes are ready for the larger hand harvest.",
    art: art("mature-radishes.png"),
    badge: "Ready",
    cropId: "radish",
    cropState: "ready",
  },
  radish_seeds: {
    name: "Radish Seeds",
    kind: "Item",
    description: "Harvest baby Radishes quickly or keep watering for a full crop.",
    art: art("radish-seeds.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "radish",
    cropState: "seeds",
  },
  hoe: {
    name: "Hoe",
    kind: "Tool",
    description: "A persistent Tool for tilling Cleared Ground into a Plot.",
    art: art("hoe.png"),
    artShape: "square",
    portable: true,
  },
  watering_can: {
    name: "Watering Can",
    kind: "Tool",
    description: "Refill it at the Stone Well, then water thirsty crops.",
    art: art("watering-can.png"),
    filledArt: art("watering-can-filled.png"),
    artShape: "square",
    portable: true,
  },
  sickle: {
    name: "Sickle",
    kind: "Tool",
    description: "Cuts grass from Wild Soil or removes a planted crop, returning its Land to an Empty Plot.",
    art: art("sickle.png"),
    artShape: "square",
    portable: true,
  },
  well: {
    name: "Stone Well",
    kind: "Well",
    description: "Refills a carried Watering Can. It never creates a container.",
    art: art("well.png"),
  },
  carrots: {
    name: "Carrots",
    kind: "Produce",
    description: "Fresh produce for the market.",
    art: art("carrots.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "carrot",
    cropState: "produce",
    sellPrice: 1,
  },
  choice_carrots: {
    name: "Choice Carrots",
    kind: "Produce",
    description: "Carrots transformed by a visible act of care. The farm remembers the first harvest.",
    art: art("carrots.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "carrot",
    cropState: "produce",
    quality: "choice",
    sellPrice: 1,
  },
  green_beans: {
    name: "Green Beans",
    kind: "Produce",
    description: "Fresh pods from a crop that keeps growing after harvest.",
    art: art("green-beans.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "green_bean",
    cropState: "produce",
    sellPrice: 1,
  },
  choice_green_beans: {
    name: "Choice Green Beans",
    kind: "Produce",
    description: "A tended vine's crisp harvest, kept distinct from ordinary Beans.",
    art: art("green-beans.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "green_bean",
    cropState: "produce",
    quality: "choice",
    sellPrice: 1,
  },
  potatoes: {
    name: "Potatoes",
    kind: "Produce",
    description: "Freshly dug Potatoes ready for the Shipping Bin.",
    art: art("potatoes.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "potato",
    cropState: "produce",
    sellPrice: 1,
  },
  choice_potatoes: {
    name: "Choice Potatoes",
    kind: "Produce",
    description: "Tended Potatoes whose care remains visible across both digs.",
    art: art("potatoes.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "potato",
    cropState: "produce",
    quality: "choice",
    sellPrice: 1,
  },
  cauliflowers: {
    name: "Cauliflowers",
    kind: "Produce",
    description: "A large, patient Spring harvest ready for the Shipping Bin.",
    art: art("cauliflowers.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "cauliflower",
    cropState: "produce",
    sellPrice: 1,
  },
  choice_cauliflowers: {
    name: "Choice Cauliflowers",
    kind: "Produce",
    description: "A long-tended harvest remembered by the farm.",
    art: art("cauliflowers.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "cauliflower",
    cropState: "produce",
    quality: "choice",
    sellPrice: 1,
  },
  radishes: {
    name: "Radishes",
    kind: "Produce",
    description: "Baby or full Radishes gathered from a deliberately timed harvest.",
    art: art("radishes.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "radish",
    cropState: "produce",
    sellPrice: 1,
  },
  choice_radishes: {
    name: "Choice Radishes",
    kind: "Produce",
    description: "Tended Radishes that preserve the memory of the player's timing choice.",
    art: art("radishes.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "radish",
    cropState: "produce",
    quality: "choice",
    sellPrice: 1,
  },
  general_store: {
    name: "General Store",
    kind: "Store",
    description: "Choose among five Spring crop behaviors. Seeds enter the Hand.",
    art: art("general-store.png"),
  },
  shipping_bin: {
    name: "Shipping Bin",
    kind: "Farm",
    description: "Ship produce now. Collect the earnings at day's end.",
    art: art("shipping-bin.png"),
  },
  home_farm_landmark: {
    name: "Home Farm",
    kind: "Landmark",
    description: "The farm's persistent landmark and travel destination.",
    art: art("home-farm-landmark.png"),
  },
  valley_town_landmark: {
    name: "Valley Town",
    kind: "Landmark",
    description: "The town's persistent landmark and travel destination.",
    art: art("valley-town-landmark.png"),
  },
});

export function cropForType(typeId) {
  const cropId = CARD_DEFS[typeId]?.cropId;
  return cropId ? CROPS[cropId] ?? null : null;
}
