export const GAME = Object.freeze({
  version: 18,
  goalCoins: 6,
  cropGrowthDays: 2,
  actionPointsPerDay: 8,
  seasonName: "Spring",
  seasonLengthDays: 7,
  weatherByDay: Object.freeze(["sunny", "sunny", "sunny", "sunny", "sunny", "rainy", "sunny"]),
  farmFieldCapacity: 2,
  wateringCanCapacity: 2,
  storageKey: "little-valley-physical-board-v18",
  legacyStorageKeys: Object.freeze(["little-valley-physical-board-v17", "little-valley-physical-board-v16"]),
});

export function weatherForDay(day) {
  return GAME.weatherByDay[(Math.max(1, day) - 1) % GAME.weatherByDay.length];
}

export const CROPS = Object.freeze({
  carrot: Object.freeze({
    id: "carrot",
    name: "Carrots",
    seedTypeId: "carrot_seeds",
    plantedTypeId: "planted_carrots",
    wateredTypeId: "watered_carrots",
    readyTypeId: "ready_carrots",
    produceTypeId: "carrots",
    growthDays: 2,
    regrowDays: 0,
    harvestAmount: 3,
    seedBundleCost: 1,
    seedBundleAmount: 1,
  }),
  green_bean: Object.freeze({
    id: "green_bean",
    name: "Green Beans",
    seedTypeId: "green_bean_seeds",
    plantedTypeId: "planted_green_beans",
    wateredTypeId: "watered_green_beans",
    readyTypeId: "ready_green_beans",
    produceTypeId: "green_beans",
    growthDays: 3,
    regrowDays: 2,
    harvestAmount: 4,
    seedBundleCost: 2,
    seedBundleAmount: 1,
  }),
});

export const ACTION_COSTS = Object.freeze({
  travel: 1,
  clear_grass: 1,
  till_soil: 1,
  refill_watering_can: 1,
  water_plot: 1,
  sow: 1,
  sow_watered: 1,
  water_crop: 1,
  harvest: 1,
  remove_crop: 1,
});

export const AREAS = Object.freeze([
  Object.freeze({ id: "farm", name: "Home Farm", landmarkId: "farm-landmark" }),
  Object.freeze({ id: "town", name: "Valley Town", landmarkId: "town-landmark" }),
]);

const art = (filename) => `./assets/${filename}`;

export const CARD_DEFS = Object.freeze({
  farmer: {
    name: "Farmer",
    kind: "Person",
    description: "Does the work, carries one item, and harvests mature crops by hand.",
    art: art("farmer.png"),
    artShape: "square",
  },
  wild_soil: {
    name: "Wild Soil",
    kind: "Land",
    description: "Grass and stones cover workable earth.",
    art: art("wild-soil.png"),
  },
  cleared_ground: {
    name: "Cleared Ground",
    kind: "Land",
    description: "The grass is cut. The firm soil still needs the Hoe.",
    art: art("cleared-ground.png"),
    badge: "Untilled",
  },
  empty_plot: {
    name: "Empty Plot",
    kind: "Land",
    description: "Cleared soil waiting for seed.",
    art: art("empty-plot.png"),
  },
  watered_empty_plot: {
    name: "Watered Plot",
    kind: "Land",
    description: "Cleared and watered soil waiting for seed.",
    art: art("watered-plot.png"),
    badge: "Watered",
  },
  planted_carrots: {
    name: "Carrot Plot",
    kind: "Crop",
    description: "Planted, but still thirsty.",
    art: art("young-carrots.png"),
    badge: "Thirsty",
    cropId: "carrot",
    cropState: "thirsty",
  },
  watered_carrots: {
    name: "Carrot Plot",
    kind: "Crop",
    description: "Watered. Growing with time.",
    art: art("watered-carrots.png"),
    badge: "Watered",
    cropId: "carrot",
    cropState: "watered",
  },
  ready_carrots: {
    name: "Mature Carrots",
    kind: "Crop",
    description: "Ready to pull from the soil.",
    art: art("harvest.png"),
    badge: "Ready",
    cropId: "carrot",
    cropState: "ready",
  },
  carrot_seeds: {
    name: "Carrot Seeds",
    kind: "Item",
    description: "A Person can pick these up for an Empty Plot.",
    art: art("carrot-seeds.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "carrot",
    cropState: "seeds",
  },
  planted_green_beans: {
    name: "Green Bean Plot",
    kind: "Crop",
    description: "Young vines are climbing, but the soil is thirsty.",
    art: art("young-green-beans.png"),
    badge: "Thirsty",
    cropId: "green_bean",
    cropState: "thirsty",
  },
  watered_green_beans: {
    name: "Green Bean Plot",
    kind: "Crop",
    description: "Watered vines grow toward their next harvest.",
    art: art("watered-green-beans.png"),
    badge: "Watered",
    cropId: "green_bean",
    cropState: "watered",
  },
  ready_green_beans: {
    name: "Mature Green Beans",
    kind: "Crop",
    description: "Ready to pick. The vines remain for another harvest.",
    art: art("mature-green-beans.png"),
    badge: "Ready",
    cropId: "green_bean",
    cropState: "ready",
  },
  green_bean_seeds: {
    name: "Green Bean Seeds",
    kind: "Item",
    description: "One seed starts a slower crop that regrows after harvest.",
    art: art("green-bean-seeds.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "green_bean",
    cropState: "seeds",
  },
  hoe: {
    name: "Hoe",
    kind: "Tool",
    description: "A persistent Tool for tilling Cleared Ground into a Plot.",
    art: art("hoe.png"),
    artShape: "square",
    portable: true,
  },
  watering_can: {
    name: "Watering Can",
    kind: "Tool",
    description: "Refill it at the Stone Well, then water thirsty crops.",
    art: art("watering-can.png"),
    filledArt: art("watering-can-filled.png"),
    artShape: "square",
    portable: true,
  },
  sickle: {
    name: "Sickle",
    kind: "Tool",
    description: "Cuts grass from Wild Soil or removes a planted crop, returning its Land to an Empty Plot.",
    art: art("sickle.png"),
    artShape: "square",
    portable: true,
  },
  well: {
    name: "Stone Well",
    kind: "Well",
    description: "Refills a carried Watering Can. It never creates a container.",
    art: art("well.png"),
  },
  carrots: {
    name: "Carrots",
    kind: "Produce",
    description: "Fresh produce for the market.",
    art: art("carrots.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "carrot",
    cropState: "produce",
  },
  green_beans: {
    name: "Green Beans",
    kind: "Produce",
    description: "Fresh pods from a crop that keeps growing after harvest.",
    art: art("green-beans.png"),
    artShape: "square",
    portable: true,
    stackable: true,
    cropId: "green_bean",
    cropState: "produce",
  },
  general_store: {
    name: "General Store",
    kind: "Store",
    description: "Choose quick Carrots or slower regrowing Green Beans. Seeds enter the Hand.",
    art: art("general-store.png"),
  },
  shipping_bin: {
    name: "Shipping Bin",
    kind: "Farm",
    description: "Ship produce now. Collect the earnings at day's end.",
    art: art("shipping-bin.png"),
  },
  home_farm_landmark: {
    name: "Home Farm",
    kind: "Landmark",
    description: "The farm's persistent landmark and travel destination.",
    art: art("home-farm-landmark.png"),
  },
  valley_town_landmark: {
    name: "Valley Town",
    kind: "Landmark",
    description: "The town's persistent landmark and travel destination.",
    art: art("valley-town-landmark.png"),
  },
});

export function cropForType(typeId) {
  const cropId = CARD_DEFS[typeId]?.cropId;
  return cropId ? CROPS[cropId] ?? null : null;
}
